/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameScopeProvider extends DelegatingScopeProvider {
}
