/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attr Ass List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.AttrAssList#getAttrAss <em>Attr Ass</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getAttrAssList()
 * @model
 * @generated
 */
public interface AttrAssList extends EObject
{
  /**
   * Returns the value of the '<em><b>Attr Ass</b></em>' containment reference list.
   * The list contents are of type {@link uk.kcl.pgt.mdd.cw.game.AttrAss}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr Ass</em>' containment reference list.
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getAttrAssList_AttrAss()
   * @model containment="true"
   * @generated
   */
  EList<AttrAss> getAttrAss();

} // AttrAssList
