/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.Block#getStmtBlock <em>Stmt Block</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
  /**
   * Returns the value of the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt Block</em>' containment reference.
   * @see #setStmtBlock(StmtBlock)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getBlock_StmtBlock()
   * @model containment="true"
   * @generated
   */
  StmtBlock getStmtBlock();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.Block#getStmtBlock <em>Stmt Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt Block</em>' containment reference.
   * @see #getStmtBlock()
   * @generated
   */
  void setStmtBlock(StmtBlock value);

} // Block
