/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.Decl#getType <em>Type</em>}</li>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.Decl#getName <em>Name</em>}</li>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.Decl#getArrSize <em>Arr Size</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getDecl()
 * @model
 * @generated
 */
public interface Decl extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getDecl_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.Decl#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getDecl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.Decl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Arr Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arr Size</em>' attribute.
   * @see #setArrSize(int)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getDecl_ArrSize()
   * @model
   * @generated
   */
  int getArrSize();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.Decl#getArrSize <em>Arr Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arr Size</em>' attribute.
   * @see #getArrSize()
   * @generated
   */
  void setArrSize(int value);

} // Decl
