/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getEndStmt()
 * @model
 * @generated
 */
public interface EndStmt extends Stmt
{
} // EndStmt
