/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
