/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.kcl.pgt.mdd.cw.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kcl.uk/pgt/mdd/cw/Game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.GameImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Attr Ass List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__ATTR_ASS_LIST = 1;

  /**
   * The feature id for the '<em><b>Decl</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__DECL = 2;

  /**
   * The feature id for the '<em><b>Init Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__INIT_BLOCK = 3;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__FUNCTIONS = 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.DeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.DeclImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getDecl()
   * @generated
   */
  int DECL = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__NAME = 1;

  /**
   * The feature id for the '<em><b>Arr Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL__ARR_SIZE = 2;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.VarDeclImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__TYPE = DECL__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Arr Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__ARR_SIZE = DECL__ARR_SIZE;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__EXPR = DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.ObjDeclImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getObjDecl()
   * @generated
   */
  int OBJ_DECL = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__TYPE = DECL__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__NAME = DECL__NAME;

  /**
   * The feature id for the '<em><b>Arr Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__ARR_SIZE = DECL__ARR_SIZE;

  /**
   * The feature id for the '<em><b>Attr Ass List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL__ATTR_ASS_LIST = DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Obj Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJ_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AttrAssListImpl <em>Attr Ass List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.AttrAssListImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAttrAssList()
   * @generated
   */
  int ATTR_ASS_LIST = 4;

  /**
   * The feature id for the '<em><b>Attr Ass</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_LIST__ATTR_ASS = 0;

  /**
   * The number of structural features of the '<em>Attr Ass List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AttrAssImpl <em>Attr Ass</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.AttrAssImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAttrAss()
   * @generated
   */
  int ATTR_ASS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS__EXPR = 1;

  /**
   * The number of structural features of the '<em>Attr Ass</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_ASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.StmtBlockImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getStmtBlock()
   * @generated
   */
  int STMT_BLOCK = 6;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Stmt Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.StmtImpl <em>Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.StmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getStmt()
   * @generated
   */
  int STMT = 7;

  /**
   * The number of structural features of the '<em>Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STMT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.IfStmtImpl <em>If Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.IfStmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getIfStmt()
   * @generated
   */
  int IF_STMT = 8;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__CONDITION = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Consequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__CONSEQUENCE = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alternative</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT__ALTERNATIVE = STMT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl <em>While Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getWhileStmt()
   * @generated
   */
  int WHILE_STMT = 9;

  /**
   * The feature id for the '<em><b>While Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STMT__WHILE_CONDITION = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STMT__STMT_BLOCK = STMT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ForStmtImpl <em>For Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.ForStmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getForStmt()
   * @generated
   */
  int FOR_STMT = 10;

  /**
   * The feature id for the '<em><b>Init Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__INIT_STMT = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__END_CONDITION = STMT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Loop Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__LOOP_STMT = STMT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT__STMT_BLOCK = STMT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>For Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.EndStmtImpl <em>End Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.EndStmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getEndStmt()
   * @generated
   */
  int END_STMT = 11;

  /**
   * The number of structural features of the '<em>End Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.AssStmtImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAssStmt()
   * @generated
   */
  int ASS_STMT = 12;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT__VAR = STMT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT__ASSIGNMENT = STMT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ass Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASS_STMT_FEATURE_COUNT = STMT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.ExpressionImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 19;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.VarImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVar()
   * @generated
   */
  int VAR = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VAR_ARRAY = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Var Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VAR_PROP = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarArrayImpl <em>Var Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.VarArrayImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarArray()
   * @generated
   */
  int VAR_ARRAY = 14;

  /**
   * The feature id for the '<em><b>Index Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_ARRAY__INDEX_EXPR = 0;

  /**
   * The number of structural features of the '<em>Var Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_ARRAY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarPropImpl <em>Var Prop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.VarPropImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarProp()
   * @generated
   */
  int VAR_PROP = 15;

  /**
   * The feature id for the '<em><b>Ext Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_PROP__EXT_ID = 0;

  /**
   * The number of structural features of the '<em>Var Prop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_PROP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.BlockImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 16;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STMT_BLOCK = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AnimBlockImpl <em>Anim Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.AnimBlockImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAnimBlock()
   * @generated
   */
  int ANIM_BLOCK = 17;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__STMT_BLOCK = BLOCK__STMT_BLOCK;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__NAME = BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obj Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__OBJ_TYPE = BLOCK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK__OBJ_NAME = BLOCK_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Anim Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANIM_BLOCK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.EventBlockImpl <em>Event Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.EventBlockImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getEventBlock()
   * @generated
   */
  int EVENT_BLOCK = 18;

  /**
   * The feature id for the '<em><b>Stmt Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__STMT_BLOCK = BLOCK__STMT_BLOCK;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK__KEY = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Event Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_BLOCK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.UnaryOperationImpl <em>Unary Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.UnaryOperationImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getUnaryOperation()
   * @generated
   */
  int UNARY_OPERATION = 20;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATION__OP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Unary Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.IntLiteralImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = END_STMT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = END_STMT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ExprVarImpl <em>Expr Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.ExprVarImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getExprVar()
   * @generated
   */
  int EXPR_VAR = 22;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_VAR__EXPR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expr Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_VAR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.kcl.pgt.mdd.cw.game.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.kcl.pgt.mdd.cw.game.impl.OperationImpl
   * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Game#getAttrAssList <em>Attr Ass List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attr Ass List</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game#getAttrAssList()
   * @see #getGame()
   * @generated
   */
  EReference getGame_AttrAssList();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.pgt.mdd.cw.game.Game#getDecl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Decl</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game#getDecl()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Decl();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Game#getInitBlock <em>Init Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game#getInitBlock()
   * @see #getGame()
   * @generated
   */
  EReference getGame_InitBlock();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.pgt.mdd.cw.game.Game#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Game#getFunctions()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Functions();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Decl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Decl
   * @generated
   */
  EClass getDecl();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Decl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Decl#getType()
   * @see #getDecl()
   * @generated
   */
  EAttribute getDecl_Type();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Decl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Decl#getName()
   * @see #getDecl()
   * @generated
   */
  EAttribute getDecl_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Decl#getArrSize <em>Arr Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arr Size</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Decl#getArrSize()
   * @see #getDecl()
   * @generated
   */
  EAttribute getDecl_ArrSize();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.VarDecl#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarDecl#getExpr()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Expr();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.ObjDecl <em>Obj Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obj Decl</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ObjDecl
   * @generated
   */
  EClass getObjDecl();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ObjDecl#getAttrAssList <em>Attr Ass List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attr Ass List</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ObjDecl#getAttrAssList()
   * @see #getObjDecl()
   * @generated
   */
  EReference getObjDecl_AttrAssList();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.AttrAssList <em>Attr Ass List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Ass List</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AttrAssList
   * @generated
   */
  EClass getAttrAssList();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.pgt.mdd.cw.game.AttrAssList#getAttrAss <em>Attr Ass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attr Ass</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AttrAssList#getAttrAss()
   * @see #getAttrAssList()
   * @generated
   */
  EReference getAttrAssList_AttrAss();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.AttrAss <em>Attr Ass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Ass</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AttrAss
   * @generated
   */
  EClass getAttrAss();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.AttrAss#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AttrAss#getName()
   * @see #getAttrAss()
   * @generated
   */
  EAttribute getAttrAss_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.AttrAss#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AttrAss#getExpr()
   * @see #getAttrAss()
   * @generated
   */
  EReference getAttrAss_Expr();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.StmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.StmtBlock
   * @generated
   */
  EClass getStmtBlock();

  /**
   * Returns the meta object for the containment reference list '{@link uk.kcl.pgt.mdd.cw.game.StmtBlock#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.StmtBlock#getStatements()
   * @see #getStmtBlock()
   * @generated
   */
  EReference getStmtBlock_Statements();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Stmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Stmt
   * @generated
   */
  EClass getStmt();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.IfStmt <em>If Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IfStmt
   * @generated
   */
  EClass getIfStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IfStmt#getCondition()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Condition();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getConsequence <em>Consequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Consequence</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IfStmt#getConsequence()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Consequence();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getAlternative <em>Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alternative</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IfStmt#getAlternative()
   * @see #getIfStmt()
   * @generated
   */
  EReference getIfStmt_Alternative();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.WhileStmt <em>While Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.WhileStmt
   * @generated
   */
  EClass getWhileStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.WhileStmt#getWhileCondition <em>While Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>While Condition</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.WhileStmt#getWhileCondition()
   * @see #getWhileStmt()
   * @generated
   */
  EReference getWhileStmt_WhileCondition();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.WhileStmt#getStmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.WhileStmt#getStmtBlock()
   * @see #getWhileStmt()
   * @generated
   */
  EReference getWhileStmt_StmtBlock();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.ForStmt <em>For Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ForStmt
   * @generated
   */
  EClass getForStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ForStmt#getInitStmt <em>Init Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ForStmt#getInitStmt()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_InitStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ForStmt#getEndCondition <em>End Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End Condition</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ForStmt#getEndCondition()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_EndCondition();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ForStmt#getLoopStmt <em>Loop Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Loop Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ForStmt#getLoopStmt()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_LoopStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ForStmt#getStmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ForStmt#getStmtBlock()
   * @see #getForStmt()
   * @generated
   */
  EReference getForStmt_StmtBlock();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.EndStmt <em>End Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.EndStmt
   * @generated
   */
  EClass getEndStmt();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.AssStmt <em>Ass Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ass Stmt</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AssStmt
   * @generated
   */
  EClass getAssStmt();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.AssStmt#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AssStmt#getVar()
   * @see #getAssStmt()
   * @generated
   */
  EReference getAssStmt_Var();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.AssStmt#getAssignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Assignment</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AssStmt#getAssignment()
   * @see #getAssStmt()
   * @generated
   */
  EReference getAssStmt_Assignment();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Var#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Var#getName()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Var#getVarArray <em>Var Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var Array</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Var#getVarArray()
   * @see #getVar()
   * @generated
   */
  EReference getVar_VarArray();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Var#getVarProp <em>Var Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var Prop</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Var#getVarProp()
   * @see #getVar()
   * @generated
   */
  EReference getVar_VarProp();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.VarArray <em>Var Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Array</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarArray
   * @generated
   */
  EClass getVarArray();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.VarArray#getIndexExpr <em>Index Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Index Expr</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarArray#getIndexExpr()
   * @see #getVarArray()
   * @generated
   */
  EReference getVarArray_IndexExpr();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.VarProp <em>Var Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Prop</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarProp
   * @generated
   */
  EClass getVarProp();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.VarProp#getExtId <em>Ext Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ext Id</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.VarProp#getExtId()
   * @see #getVarProp()
   * @generated
   */
  EAttribute getVarProp_ExtId();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Block#getStmtBlock <em>Stmt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Block#getStmtBlock()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_StmtBlock();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.AnimBlock <em>Anim Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Anim Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AnimBlock
   * @generated
   */
  EClass getAnimBlock();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.AnimBlock#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AnimBlock#getName()
   * @see #getAnimBlock()
   * @generated
   */
  EAttribute getAnimBlock_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.AnimBlock#getObjType <em>Obj Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Type</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AnimBlock#getObjType()
   * @see #getAnimBlock()
   * @generated
   */
  EAttribute getAnimBlock_ObjType();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.AnimBlock#getObjName <em>Obj Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Name</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.AnimBlock#getObjName()
   * @see #getAnimBlock()
   * @generated
   */
  EAttribute getAnimBlock_ObjName();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.EventBlock <em>Event Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Block</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.EventBlock
   * @generated
   */
  EClass getEventBlock();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.EventBlock#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.EventBlock#getKey()
   * @see #getEventBlock()
   * @generated
   */
  EAttribute getEventBlock_Key();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.UnaryOperation <em>Unary Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Operation</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.UnaryOperation
   * @generated
   */
  EClass getUnaryOperation();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.UnaryOperation#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.UnaryOperation#getOp()
   * @see #getUnaryOperation()
   * @generated
   */
  EAttribute getUnaryOperation_Op();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.UnaryOperation#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.UnaryOperation#getRight()
   * @see #getUnaryOperation()
   * @generated
   */
  EReference getUnaryOperation_Right();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.IntLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.IntLiteral#getValue()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Value();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.ExprVar <em>Expr Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Var</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ExprVar
   * @generated
   */
  EClass getExprVar();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.ExprVar#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.ExprVar#getExpr()
   * @see #getExprVar()
   * @generated
   */
  EReference getExprVar_Expr();

  /**
   * Returns the meta object for class '{@link uk.kcl.pgt.mdd.cw.game.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Operation#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Operation#getLeft()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Left();

  /**
   * Returns the meta object for the attribute '{@link uk.kcl.pgt.mdd.cw.game.Operation#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Operation#getOp()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Op();

  /**
   * Returns the meta object for the containment reference '{@link uk.kcl.pgt.mdd.cw.game.Operation#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see uk.kcl.pgt.mdd.cw.game.Operation#getRight()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.GameImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Attr Ass List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__ATTR_ASS_LIST = eINSTANCE.getGame_AttrAssList();

    /**
     * The meta object literal for the '<em><b>Decl</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__DECL = eINSTANCE.getGame_Decl();

    /**
     * The meta object literal for the '<em><b>Init Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__INIT_BLOCK = eINSTANCE.getGame_InitBlock();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__FUNCTIONS = eINSTANCE.getGame_Functions();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.DeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.DeclImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getDecl()
     * @generated
     */
    EClass DECL = eINSTANCE.getDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECL__TYPE = eINSTANCE.getDecl_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECL__NAME = eINSTANCE.getDecl_Name();

    /**
     * The meta object literal for the '<em><b>Arr Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECL__ARR_SIZE = eINSTANCE.getDecl_ArrSize();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.VarDeclImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__EXPR = eINSTANCE.getVarDecl_Expr();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ObjDeclImpl <em>Obj Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.ObjDeclImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getObjDecl()
     * @generated
     */
    EClass OBJ_DECL = eINSTANCE.getObjDecl();

    /**
     * The meta object literal for the '<em><b>Attr Ass List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJ_DECL__ATTR_ASS_LIST = eINSTANCE.getObjDecl_AttrAssList();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AttrAssListImpl <em>Attr Ass List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.AttrAssListImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAttrAssList()
     * @generated
     */
    EClass ATTR_ASS_LIST = eINSTANCE.getAttrAssList();

    /**
     * The meta object literal for the '<em><b>Attr Ass</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTR_ASS_LIST__ATTR_ASS = eINSTANCE.getAttrAssList_AttrAss();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AttrAssImpl <em>Attr Ass</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.AttrAssImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAttrAss()
     * @generated
     */
    EClass ATTR_ASS = eINSTANCE.getAttrAss();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_ASS__NAME = eINSTANCE.getAttrAss_Name();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTR_ASS__EXPR = eINSTANCE.getAttrAss_Expr();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.StmtBlockImpl <em>Stmt Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.StmtBlockImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getStmtBlock()
     * @generated
     */
    EClass STMT_BLOCK = eINSTANCE.getStmtBlock();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STMT_BLOCK__STATEMENTS = eINSTANCE.getStmtBlock_Statements();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.StmtImpl <em>Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.StmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getStmt()
     * @generated
     */
    EClass STMT = eINSTANCE.getStmt();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.IfStmtImpl <em>If Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.IfStmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getIfStmt()
     * @generated
     */
    EClass IF_STMT = eINSTANCE.getIfStmt();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__CONDITION = eINSTANCE.getIfStmt_Condition();

    /**
     * The meta object literal for the '<em><b>Consequence</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__CONSEQUENCE = eINSTANCE.getIfStmt_Consequence();

    /**
     * The meta object literal for the '<em><b>Alternative</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STMT__ALTERNATIVE = eINSTANCE.getIfStmt_Alternative();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl <em>While Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getWhileStmt()
     * @generated
     */
    EClass WHILE_STMT = eINSTANCE.getWhileStmt();

    /**
     * The meta object literal for the '<em><b>While Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_STMT__WHILE_CONDITION = eINSTANCE.getWhileStmt_WhileCondition();

    /**
     * The meta object literal for the '<em><b>Stmt Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_STMT__STMT_BLOCK = eINSTANCE.getWhileStmt_StmtBlock();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ForStmtImpl <em>For Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.ForStmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getForStmt()
     * @generated
     */
    EClass FOR_STMT = eINSTANCE.getForStmt();

    /**
     * The meta object literal for the '<em><b>Init Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__INIT_STMT = eINSTANCE.getForStmt_InitStmt();

    /**
     * The meta object literal for the '<em><b>End Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__END_CONDITION = eINSTANCE.getForStmt_EndCondition();

    /**
     * The meta object literal for the '<em><b>Loop Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__LOOP_STMT = eINSTANCE.getForStmt_LoopStmt();

    /**
     * The meta object literal for the '<em><b>Stmt Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STMT__STMT_BLOCK = eINSTANCE.getForStmt_StmtBlock();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.EndStmtImpl <em>End Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.EndStmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getEndStmt()
     * @generated
     */
    EClass END_STMT = eINSTANCE.getEndStmt();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AssStmtImpl <em>Ass Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.AssStmtImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAssStmt()
     * @generated
     */
    EClass ASS_STMT = eINSTANCE.getAssStmt();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASS_STMT__VAR = eINSTANCE.getAssStmt_Var();

    /**
     * The meta object literal for the '<em><b>Assignment</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASS_STMT__ASSIGNMENT = eINSTANCE.getAssStmt_Assignment();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.VarImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__NAME = eINSTANCE.getVar_Name();

    /**
     * The meta object literal for the '<em><b>Var Array</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__VAR_ARRAY = eINSTANCE.getVar_VarArray();

    /**
     * The meta object literal for the '<em><b>Var Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR__VAR_PROP = eINSTANCE.getVar_VarProp();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarArrayImpl <em>Var Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.VarArrayImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarArray()
     * @generated
     */
    EClass VAR_ARRAY = eINSTANCE.getVarArray();

    /**
     * The meta object literal for the '<em><b>Index Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_ARRAY__INDEX_EXPR = eINSTANCE.getVarArray_IndexExpr();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.VarPropImpl <em>Var Prop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.VarPropImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getVarProp()
     * @generated
     */
    EClass VAR_PROP = eINSTANCE.getVarProp();

    /**
     * The meta object literal for the '<em><b>Ext Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_PROP__EXT_ID = eINSTANCE.getVarProp_ExtId();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.BlockImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Stmt Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STMT_BLOCK = eINSTANCE.getBlock_StmtBlock();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.AnimBlockImpl <em>Anim Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.AnimBlockImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getAnimBlock()
     * @generated
     */
    EClass ANIM_BLOCK = eINSTANCE.getAnimBlock();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANIM_BLOCK__NAME = eINSTANCE.getAnimBlock_Name();

    /**
     * The meta object literal for the '<em><b>Obj Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANIM_BLOCK__OBJ_TYPE = eINSTANCE.getAnimBlock_ObjType();

    /**
     * The meta object literal for the '<em><b>Obj Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANIM_BLOCK__OBJ_NAME = eINSTANCE.getAnimBlock_ObjName();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.EventBlockImpl <em>Event Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.EventBlockImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getEventBlock()
     * @generated
     */
    EClass EVENT_BLOCK = eINSTANCE.getEventBlock();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_BLOCK__KEY = eINSTANCE.getEventBlock_Key();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.ExpressionImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.UnaryOperationImpl <em>Unary Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.UnaryOperationImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getUnaryOperation()
     * @generated
     */
    EClass UNARY_OPERATION = eINSTANCE.getUnaryOperation();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_OPERATION__OP = eINSTANCE.getUnaryOperation_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_OPERATION__RIGHT = eINSTANCE.getUnaryOperation_Right();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.IntLiteralImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getIntLiteral_Value();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.ExprVarImpl <em>Expr Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.ExprVarImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getExprVar()
     * @generated
     */
    EClass EXPR_VAR = eINSTANCE.getExprVar();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_VAR__EXPR = eINSTANCE.getExprVar_Expr();

    /**
     * The meta object literal for the '{@link uk.kcl.pgt.mdd.cw.game.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.kcl.pgt.mdd.cw.game.impl.OperationImpl
     * @see uk.kcl.pgt.mdd.cw.game.impl.GamePackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__LEFT = eINSTANCE.getOperation_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OP = eINSTANCE.getOperation_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__RIGHT = eINSTANCE.getOperation_Right();

  }

} //GamePackage
