/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getCondition <em>Condition</em>}</li>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getConsequence <em>Consequence</em>}</li>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getAlternative <em>Alternative</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getIfStmt()
 * @model
 * @generated
 */
public interface IfStmt extends Stmt
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getIfStmt_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>Consequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consequence</em>' containment reference.
   * @see #setConsequence(StmtBlock)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getIfStmt_Consequence()
   * @model containment="true"
   * @generated
   */
  StmtBlock getConsequence();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getConsequence <em>Consequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consequence</em>' containment reference.
   * @see #getConsequence()
   * @generated
   */
  void setConsequence(StmtBlock value);

  /**
   * Returns the value of the '<em><b>Alternative</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alternative</em>' containment reference.
   * @see #setAlternative(StmtBlock)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getIfStmt_Alternative()
   * @model containment="true"
   * @generated
   */
  StmtBlock getAlternative();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.IfStmt#getAlternative <em>Alternative</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alternative</em>' containment reference.
   * @see #getAlternative()
   * @generated
   */
  void setAlternative(StmtBlock value);

} // IfStmt
