/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obj Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.ObjDecl#getAttrAssList <em>Attr Ass List</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getObjDecl()
 * @model
 * @generated
 */
public interface ObjDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Attr Ass List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr Ass List</em>' containment reference.
   * @see #setAttrAssList(AttrAssList)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getObjDecl_AttrAssList()
   * @model containment="true"
   * @generated
   */
  AttrAssList getAttrAssList();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.ObjDecl#getAttrAssList <em>Attr Ass List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attr Ass List</em>' containment reference.
   * @see #getAttrAssList()
   * @generated
   */
  void setAttrAssList(AttrAssList value);

} // ObjDecl
