/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getStmt()
 * @model
 * @generated
 */
public interface Stmt extends EObject
{
} // Stmt
