/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Prop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.VarProp#getExtId <em>Ext Id</em>}</li>
 * </ul>
 *
 * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getVarProp()
 * @model
 * @generated
 */
public interface VarProp extends EObject
{
  /**
   * Returns the value of the '<em><b>Ext Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ext Id</em>' attribute.
   * @see #setExtId(String)
   * @see uk.kcl.pgt.mdd.cw.game.GamePackage#getVarProp_ExtId()
   * @model
   * @generated
   */
  String getExtId();

  /**
   * Sets the value of the '{@link uk.kcl.pgt.mdd.cw.game.VarProp#getExtId <em>Ext Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ext Id</em>' attribute.
   * @see #getExtId()
   * @generated
   */
  void setExtId(String value);

} // VarProp
