/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GameUiModule extends AbstractGameUiModule {

	public GameUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
