/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game.impl;

import org.eclipse.emf.ecore.EClass;

import uk.kcl.pgt.mdd.cw.game.EndStmt;
import uk.kcl.pgt.mdd.cw.game.GamePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>End Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EndStmtImpl extends StmtImpl implements EndStmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EndStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.END_STMT;
  }

} //EndStmtImpl
