/**
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.game.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.kcl.pgt.mdd.cw.game.Expression;
import uk.kcl.pgt.mdd.cw.game.GamePackage;
import uk.kcl.pgt.mdd.cw.game.StmtBlock;
import uk.kcl.pgt.mdd.cw.game.WhileStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>While Stmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl#getWhileCondition <em>While Condition</em>}</li>
 *   <li>{@link uk.kcl.pgt.mdd.cw.game.impl.WhileStmtImpl#getStmtBlock <em>Stmt Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WhileStmtImpl extends StmtImpl implements WhileStmt
{
  /**
   * The cached value of the '{@link #getWhileCondition() <em>While Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhileCondition()
   * @generated
   * @ordered
   */
  protected Expression whileCondition;

  /**
   * The cached value of the '{@link #getStmtBlock() <em>Stmt Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStmtBlock()
   * @generated
   * @ordered
   */
  protected StmtBlock stmtBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WhileStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.WHILE_STMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getWhileCondition()
  {
    return whileCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhileCondition(Expression newWhileCondition, NotificationChain msgs)
  {
    Expression oldWhileCondition = whileCondition;
    whileCondition = newWhileCondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.WHILE_STMT__WHILE_CONDITION, oldWhileCondition, newWhileCondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWhileCondition(Expression newWhileCondition)
  {
    if (newWhileCondition != whileCondition)
    {
      NotificationChain msgs = null;
      if (whileCondition != null)
        msgs = ((InternalEObject)whileCondition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.WHILE_STMT__WHILE_CONDITION, null, msgs);
      if (newWhileCondition != null)
        msgs = ((InternalEObject)newWhileCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.WHILE_STMT__WHILE_CONDITION, null, msgs);
      msgs = basicSetWhileCondition(newWhileCondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.WHILE_STMT__WHILE_CONDITION, newWhileCondition, newWhileCondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StmtBlock getStmtBlock()
  {
    return stmtBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStmtBlock(StmtBlock newStmtBlock, NotificationChain msgs)
  {
    StmtBlock oldStmtBlock = stmtBlock;
    stmtBlock = newStmtBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.WHILE_STMT__STMT_BLOCK, oldStmtBlock, newStmtBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStmtBlock(StmtBlock newStmtBlock)
  {
    if (newStmtBlock != stmtBlock)
    {
      NotificationChain msgs = null;
      if (stmtBlock != null)
        msgs = ((InternalEObject)stmtBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.WHILE_STMT__STMT_BLOCK, null, msgs);
      if (newStmtBlock != null)
        msgs = ((InternalEObject)newStmtBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.WHILE_STMT__STMT_BLOCK, null, msgs);
      msgs = basicSetStmtBlock(newStmtBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.WHILE_STMT__STMT_BLOCK, newStmtBlock, newStmtBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.WHILE_STMT__WHILE_CONDITION:
        return basicSetWhileCondition(null, msgs);
      case GamePackage.WHILE_STMT__STMT_BLOCK:
        return basicSetStmtBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.WHILE_STMT__WHILE_CONDITION:
        return getWhileCondition();
      case GamePackage.WHILE_STMT__STMT_BLOCK:
        return getStmtBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.WHILE_STMT__WHILE_CONDITION:
        setWhileCondition((Expression)newValue);
        return;
      case GamePackage.WHILE_STMT__STMT_BLOCK:
        setStmtBlock((StmtBlock)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.WHILE_STMT__WHILE_CONDITION:
        setWhileCondition((Expression)null);
        return;
      case GamePackage.WHILE_STMT__STMT_BLOCK:
        setStmtBlock((StmtBlock)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.WHILE_STMT__WHILE_CONDITION:
        return whileCondition != null;
      case GamePackage.WHILE_STMT__STMT_BLOCK:
        return stmtBlock != null;
    }
    return super.eIsSet(featureID);
  }

} //WhileStmtImpl
