/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.kcl.pgt.mdd.cw.Game.ui.internal.GameActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GameActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GameActivator activator = GameActivator.getInstance();
		return activator != null ? activator.getInjector(GameActivator.UK_KCL_PGT_MDD_CW_GAME) : null;
	}

}
