/*
 * generated by Xtext 2.24.0
 */
package uk.kcl.pgt.mdd.cw;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GameRuntimeModule extends AbstractGameRuntimeModule {
}
